swagger: "2.0"
info:
  title: Bank Argent API Documentation
  description: Contains all available API endpoints in this codebase
  version: 1.0.0
  termsOfService: "http://swagger.io/terms/"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User's Accounts API
      description: API for getting user's accounts
      responses:
        "200":
          description: User's accounts retrieved successfully
          schema:
            $ref: "#/definitions/UserAccount"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Account Transactions API
      description: API for getting accounts's transactions
      parameters:
        - in: path
          name: accountId
          description: User's account ID
          type: integer
          required: true
      responses:
        "200":
          description: Account's transactions retrieved successfully
          schema:
            $ref: "#/definitions/AccountTransactions"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transactions/{transactionId}/category:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Account Transactions API
      description: API to change the transaction category
      parameters:
        - in: body
          name: body
          description: Change the details of the transaction
          required: true
          schema:
            $ref: "#/definitions/ChangeTransactionDetailsCategory"
        - in: path
          name: transactionId
          description: Account's transaction ID
          type: integer
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
  /user/transactions/{transactionId}/note:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Account Transactions API
      description: API to change the transaction's note
      parameters:
        - in: body
          name: body
          description: Change the details of the transaction
          required: true
          schema:
            $ref: "#/definitions/ChangeTransactionDetailsNote"
        - in: path
          name: transactionId
          description: Account's transaction ID
          type: integer
          required: true
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/ApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  UserAccount:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            name:
              type: string
            balance:
              type: string
            category:
              type: string
  AccountTransactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
            month:
              type: string
            date:
              type: string
            description:
              type: string
            amount:
              type: string
            balance:
              type: string
            type:
              type: string
            category:
              type: string
            note:
              type: string
  ChangeTransactionDetailsCategory:
    type: object
    properties:
      category:
        type: string
  ChangeTransactionDetailsNote:
    type: object
    properties:
      note:
        type: string
